// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-arcade/arcade/internal/agent/bootstrap"
	"github.com/go-arcade/arcade/internal/agent/config"
	"github.com/go-arcade/arcade/internal/agent/router"
	"github.com/go-arcade/arcade/pkg/log"
)

// Injectors from wire.go:

func initAgent(configPath string) (*bootstrap.Agent, func(), error) {
	agentConfig := config.NewConf(configPath)
	http := config.ProvideHttpConfig(agentConfig)
	routerRouter := router.ProvideRouter(http)
	conf := config.ProvideLogConfig(agentConfig)
	logger, err := log.ProvideLogger(conf)
	if err != nil {
		return nil, nil, err
	}
	agent, cleanup, err := bootstrap.NewAgent(routerRouter, logger, agentConfig)
	if err != nil {
		return nil, nil, err
	}
	return agent, func() {
		cleanup()
	}, nil
}
