// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-arcade/arcade/internal/agent/bootstrap"
	"github.com/go-arcade/arcade/internal/agent/config"
	"github.com/go-arcade/arcade/internal/agent/router"
	"github.com/go-arcade/arcade/internal/pkg/grpc"
	"github.com/go-arcade/arcade/internal/pkg/queue"
	"github.com/go-arcade/arcade/pkg/cache"
	"github.com/go-arcade/arcade/pkg/log"
	"github.com/go-arcade/arcade/pkg/metrics"
	"github.com/go-arcade/arcade/pkg/pprof"
)

// Injectors from wire.go:

func initAgent(configPath string) (*bootstrap.Agent, func(), error) {
	agentConfig := config.NewConf(configPath)
	http := config.ProvideHttpConfig(agentConfig)
	routerRouter := router.ProvideRouter(http)
	clientConf := config.ProvideGrpcClientConfig(agentConfig)
	clientWrapper, err := grpc.ProvideGrpcClient(clientConf)
	if err != nil {
		return nil, nil, err
	}
	redis := config.ProvideRedisConfig(agentConfig)
	client, err := cache.ProvideRedis(redis)
	if err != nil {
		return nil, nil, err
	}
	queueConfig := queue.ProvideAgentConfig(agentConfig, client)
	queueClient, err := queue.ProvideQueueClient(queueConfig)
	if err != nil {
		return nil, nil, err
	}
	metricsConfig := config.ProvideMetricsConfig(agentConfig)
	server := metrics.NewMetricsServer(metricsConfig)
	pprofConfig := config.ProvidePprofConfig(agentConfig)
	pprofServer := pprof.NewPprofServer(pprofConfig)
	conf := config.ProvideLogConfig(agentConfig)
	logger, err := log.ProvideLogger(conf)
	if err != nil {
		return nil, nil, err
	}
	pipelineTaskHandler := queue.ProvidePipelineTaskHandler()
	jobTaskHandler := queue.ProvideJobTaskHandler()
	stepTaskHandler := queue.ProvideStepTaskHandler()
	agent, cleanup, err := bootstrap.NewAgent(routerRouter, clientWrapper, queueClient, server, pprofServer, logger, agentConfig, pipelineTaskHandler, jobTaskHandler, stepTaskHandler)
	if err != nil {
		return nil, nil, err
	}
	return agent, func() {
		cleanup()
	}, nil
}
