// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/stream/v1/stream.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stream_StreamJobLog_FullMethodName         = "/api.stream.v1.Stream/StreamJobLog"
	Stream_UploadJobLog_FullMethodName         = "/api.stream.v1.Stream/UploadJobLog"
	Stream_StreamJobStatus_FullMethodName      = "/api.stream.v1.Stream/StreamJobStatus"
	Stream_StreamPipelineStatus_FullMethodName = "/api.stream.v1.Stream/StreamPipelineStatus"
	Stream_AgentChannel_FullMethodName         = "/api.stream.v1.Stream/AgentChannel"
	Stream_StreamAgentStatus_FullMethodName    = "/api.stream.v1.Stream/StreamAgentStatus"
	Stream_StreamEvents_FullMethodName         = "/api.stream.v1.Stream/StreamEvents"
)

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stream服务 - 实时数据流传输接口
type StreamClient interface {
	// 实时获取任务日志流 - Server端流式推送日志给客户端
	StreamJobLog(ctx context.Context, in *StreamJobLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamJobLogResponse], error)
	// 上报任务日志流 - Agent端流式上报日志给Server
	UploadJobLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadJobLogRequest, UploadJobLogResponse], error)
	// 实时获取任务状态流 - Server端流式推送任务状态变化
	StreamJobStatus(ctx context.Context, in *StreamJobStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamJobStatusResponse], error)
	// 实时获取流水线状态流 - Server端流式推送流水线状态变化
	StreamPipelineStatus(ctx context.Context, in *StreamPipelineStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPipelineStatusResponse], error)
	// Agent与Server双向通信流 - 用于实时任务调度和控制
	AgentChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentChannelRequest, AgentChannelResponse], error)
	// 实时监控Agent状态流 - Server端流式推送Agent状态变化
	StreamAgentStatus(ctx context.Context, in *StreamAgentStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAgentStatusResponse], error)
	// 实时事件流 - Server端推送系统事件
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
}

type streamClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamClient(cc grpc.ClientConnInterface) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) StreamJobLog(ctx context.Context, in *StreamJobLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamJobLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[0], Stream_StreamJobLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobLogRequest, StreamJobLogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamJobLogClient = grpc.ServerStreamingClient[StreamJobLogResponse]

func (c *streamClient) UploadJobLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadJobLogRequest, UploadJobLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[1], Stream_UploadJobLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadJobLogRequest, UploadJobLogResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_UploadJobLogClient = grpc.ClientStreamingClient[UploadJobLogRequest, UploadJobLogResponse]

func (c *streamClient) StreamJobStatus(ctx context.Context, in *StreamJobStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamJobStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[2], Stream_StreamJobStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobStatusRequest, StreamJobStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamJobStatusClient = grpc.ServerStreamingClient[StreamJobStatusResponse]

func (c *streamClient) StreamPipelineStatus(ctx context.Context, in *StreamPipelineStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamPipelineStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[3], Stream_StreamPipelineStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPipelineStatusRequest, StreamPipelineStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamPipelineStatusClient = grpc.ServerStreamingClient[StreamPipelineStatusResponse]

func (c *streamClient) AgentChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentChannelRequest, AgentChannelResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[4], Stream_AgentChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentChannelRequest, AgentChannelResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_AgentChannelClient = grpc.BidiStreamingClient[AgentChannelRequest, AgentChannelResponse]

func (c *streamClient) StreamAgentStatus(ctx context.Context, in *StreamAgentStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamAgentStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[5], Stream_StreamAgentStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAgentStatusRequest, StreamAgentStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamAgentStatusClient = grpc.ServerStreamingClient[StreamAgentStatusResponse]

func (c *streamClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[6], Stream_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

// StreamServer is the server API for Stream service.
// All implementations must embed UnimplementedStreamServer
// for forward compatibility.
//
// Stream服务 - 实时数据流传输接口
type StreamServer interface {
	// 实时获取任务日志流 - Server端流式推送日志给客户端
	StreamJobLog(*StreamJobLogRequest, grpc.ServerStreamingServer[StreamJobLogResponse]) error
	// 上报任务日志流 - Agent端流式上报日志给Server
	UploadJobLog(grpc.ClientStreamingServer[UploadJobLogRequest, UploadJobLogResponse]) error
	// 实时获取任务状态流 - Server端流式推送任务状态变化
	StreamJobStatus(*StreamJobStatusRequest, grpc.ServerStreamingServer[StreamJobStatusResponse]) error
	// 实时获取流水线状态流 - Server端流式推送流水线状态变化
	StreamPipelineStatus(*StreamPipelineStatusRequest, grpc.ServerStreamingServer[StreamPipelineStatusResponse]) error
	// Agent与Server双向通信流 - 用于实时任务调度和控制
	AgentChannel(grpc.BidiStreamingServer[AgentChannelRequest, AgentChannelResponse]) error
	// 实时监控Agent状态流 - Server端流式推送Agent状态变化
	StreamAgentStatus(*StreamAgentStatusRequest, grpc.ServerStreamingServer[StreamAgentStatusResponse]) error
	// 实时事件流 - Server端推送系统事件
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	mustEmbedUnimplementedStreamServer()
}

// UnimplementedStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServer struct{}

func (UnimplementedStreamServer) StreamJobLog(*StreamJobLogRequest, grpc.ServerStreamingServer[StreamJobLogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobLog not implemented")
}
func (UnimplementedStreamServer) UploadJobLog(grpc.ClientStreamingServer[UploadJobLogRequest, UploadJobLogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadJobLog not implemented")
}
func (UnimplementedStreamServer) StreamJobStatus(*StreamJobStatusRequest, grpc.ServerStreamingServer[StreamJobStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamJobStatus not implemented")
}
func (UnimplementedStreamServer) StreamPipelineStatus(*StreamPipelineStatusRequest, grpc.ServerStreamingServer[StreamPipelineStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPipelineStatus not implemented")
}
func (UnimplementedStreamServer) AgentChannel(grpc.BidiStreamingServer[AgentChannelRequest, AgentChannelResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AgentChannel not implemented")
}
func (UnimplementedStreamServer) StreamAgentStatus(*StreamAgentStatusRequest, grpc.ServerStreamingServer[StreamAgentStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAgentStatus not implemented")
}
func (UnimplementedStreamServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedStreamServer) mustEmbedUnimplementedStreamServer() {}
func (UnimplementedStreamServer) testEmbeddedByValue()                {}

// UnsafeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServer will
// result in compilation errors.
type UnsafeStreamServer interface {
	mustEmbedUnimplementedStreamServer()
}

func RegisterStreamServer(s grpc.ServiceRegistrar, srv StreamServer) {
	// If the following call pancis, it indicates UnimplementedStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stream_ServiceDesc, srv)
}

func _Stream_StreamJobLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).StreamJobLog(m, &grpc.GenericServerStream[StreamJobLogRequest, StreamJobLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamJobLogServer = grpc.ServerStreamingServer[StreamJobLogResponse]

func _Stream_UploadJobLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).UploadJobLog(&grpc.GenericServerStream[UploadJobLogRequest, UploadJobLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_UploadJobLogServer = grpc.ClientStreamingServer[UploadJobLogRequest, UploadJobLogResponse]

func _Stream_StreamJobStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).StreamJobStatus(m, &grpc.GenericServerStream[StreamJobStatusRequest, StreamJobStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamJobStatusServer = grpc.ServerStreamingServer[StreamJobStatusResponse]

func _Stream_StreamPipelineStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPipelineStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).StreamPipelineStatus(m, &grpc.GenericServerStream[StreamPipelineStatusRequest, StreamPipelineStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamPipelineStatusServer = grpc.ServerStreamingServer[StreamPipelineStatusResponse]

func _Stream_AgentChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).AgentChannel(&grpc.GenericServerStream[AgentChannelRequest, AgentChannelResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_AgentChannelServer = grpc.BidiStreamingServer[AgentChannelRequest, AgentChannelResponse]

func _Stream_StreamAgentStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAgentStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).StreamAgentStatus(m, &grpc.GenericServerStream[StreamAgentStatusRequest, StreamAgentStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamAgentStatusServer = grpc.ServerStreamingServer[StreamAgentStatusResponse]

func _Stream_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Stream_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

// Stream_ServiceDesc is the grpc.ServiceDesc for Stream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.stream.v1.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobLog",
			Handler:       _Stream_StreamJobLog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadJobLog",
			Handler:       _Stream_UploadJobLog_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamJobStatus",
			Handler:       _Stream_StreamJobStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPipelineStatus",
			Handler:       _Stream_StreamPipelineStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AgentChannel",
			Handler:       _Stream_AgentChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamAgentStatus",
			Handler:       _Stream_StreamAgentStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Stream_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/stream/v1/stream.proto",
}
